#
# Very simple makefile for coursework 1. You should not need to update this
# since you should only edit the file cwk1.c for this assignment.
#
EXE = cwk1
CC = gcc
CCFLAGS = -Wall -fopenmp -std=c99

all:
	$(CC) $(CCFLAGS) -o $(EXE) cwk1.c

